export const foodMenu = [
  {
    category: "BREAKFAST",
    image: "/images/Cheese-Omelette.jpeg",
    items: [
      { name: "Full English Breakfast", price: 12000 },
      { name: "French Toast / Honey Toast", price: 3000 },
      { name: "Scrambled Egg", price: 3000 },
      { name: "Spanish Omelette, Omelette", price: 2000 },
      { name: "Cheese Omelette", price: 3000 },
      { name: "Plantain Fritata", price: 5000 },
      { name: "Egg Sauce", price: 3000 },
      { name: "Tea or Coffee", price: 3000 },
      { name: "Beans Porridge", price: 2000 },
      { name: "Plantain", price: 2000 },
      { name: "Boiled Potato", price: 2000 },
      { name: "Fried Yam", price: 2000 },
    ],
  },
  {
    category: "HOT APPETIZER",
    image: "/images/Crispy-Chicken-Wings.jpeg",
    items: [
      { name: "Spicy Chicken Wings", price: 7000 },
      { name: "Sweet Corn Soup", price: 3500 },
      { name: "Creamy Mushroom Soup", price: 3500 },
      { name: "Catfish Pepper Soup", price: 6000 },
      { name: "Goat Meat Pepper Soup", price: 6000 },
      { name: "Croaker Pepper Soup", price: 6000 },
      { name: "Spring Roll (3 pieces)", price: 3000 },
      { name: "Samosa (3 pieces)", price: 3000 },
    ],
  },
  {
    category: "FRIES",
    image: "/images/French-Fries.jpeg",
    items: [
      { name: "French Fries", price: 3000 },
      { name: "Chicken and Fries", price: 6000 },
      { name: "Loaded fries: Small", price: 8000 },
      { name: "Loaded fries: Big", price: 12000 },
      { name: "Roasted plantain with Fish sauc", price: 8000 },
    ],
  },
  {
    category: "MAIN DISH (Rice)",
    image: "/images/Nigerian-fried-rice.jpeg",
    items: [
      { name: "Jollof", price: 2000 },
      { name: "Fried Rice", price: 2000 },
      { name: "Coconut Rice", price: 7000 },
      { name: "Our Signature Rice", price: 9500 },
      { name: "Spanish Rice", price: 9000 },
      { name: "Orienta Rice", price: 9000 },
      { name: "Asun Rice", price: 6000 },
      { name: "White Rice", price: 2000 },
    ],
  },
  {
    category: "NATIONAL DELICACIES",
    image: "/images/Spicy-Peppered-GOATMEAT.jpeg",
    items: [
      { name: "Goat Meat", price: 2000 },
      { name: "Ice Fish", price: 3000 },
      { name: "Pomo", price: 1000 },
      { name: "Sharkl", price: 2000 },
      { name: "Snail", price: 3500 },
      { name: "Dry Fish", price: 4000 },
      { name: "Beef", price: 2000 },
      { name: "Ofada Rice & Sauce", price: 5500 },
    ],
  },
  {
    category: "CYLUX PLATER",
    image: "/images/img-28.jpeg",
    items: [
      { name: "Small", price: 25000 },
      { name: "Medium", price: 35000 },
      { name: "Executive Plater", price: 50000 },
      { name: "Chow-Mein", price: 10000 },
      { name: "Chinese Fried Rice", price: 7000 },
      { name: "China Hot Pot", price: 12000 },
      { name: "Vegetable Fried Rice", price: 4000 },
      { name: "Lo-Mein", price: 10000 },
      { name: "Spicy Fried Chicken", price: 10000 },
      { name: "Kung Pao Chicken", price: 12000 },
      { name: "Shrimps Stir Fried", price: 8000 },
      { name: "Chili Vegetable Prawns", price: 18000 },
      { name: "Noodles Lein_Mein", price: 12000 },
      { name: "Sichuan Boiled Pork", price: 15000 },
    ],
  },
  {
    category: "CYLUX SPECIAL POT",
    image: "/images/Nwobi.jpeg",
    items: [
      { name: "Pepper Turkey", price: 9000 },
      { name: "Pepper Cow Leg", price: 7000 },
      { name: "Pepper Goatmeat", price: 6000 },
      { name: "Pepper Beef", price: 8000 },
      { name: "Pepper Chicken", price: 7000 },
      { name: "Pepper Snail", price: 8000 },
      { name: "Bush Meat, Alligator, or grass cutter", price: 8000 },
      { name: "Isi_Ewu", price: 14000 },
      { name: "Nkwobi", price: 10000 },
    ],
  },
  {
    category: "SOFT/ENERGY DRINKS",
    image: "/images/soft-drink.jpeg",
    items: [
      { name: "Coke", price: 1000 },
      { name: "Fanta", price: 1000 },
      { name: "Sprite", price: 1000 },
      { name: "Water", price: 500 },
      { name: "Malt", price: 1300 },
      { name: "Fearless", price: 1000 },
      { name: "Climax", price: 1000 },
      { name: "Monster", price: 1500 },
      { name: "Fayrouz", price: 1200 },
      { name: "Schwepps", price: 1000 },
    ],
  },
  {
    category: "SMOOTHIES",
    image: "/images/Strawberry-Smoothie.jpeg",
    items: [
      { name: "Cylux-Fantasy", price: 5000 },
      { name: "Fibre Thriller", price: 5000 },
      { name: "One More Night", price: 5000 },
      { name: "Pink Lady", price: 5000 },
      { name: "Califonia Love", price: 5000 },
      { name: "Green Goddess", price: 5000 },
      { name: "Sugar Daddy", price: 4500 },
      { name: "Caves Men Strength", price: 4500 },
      { name: "French Kiss", price: 4500 },
      { name: "Banana & Ginger", price: 4500 },
      { name: "Monkey Drama", price: 5000 },
      { name: "Strawberry Seduction", price: 5000 },
      { name: "Fantasy Extract", price: 5000 },
      { name: "Booze Hardshake", price: 5000 },
    ],
  },
  {
    category: "BEER DRINKS",
    image: "/images/beer.jpeg",
    items: [
      { name: "Heineken", price: 2000 },
      { name: "Budweiser", price: 2000 },
      { name: "Medium stout", price: 2000 },
      { name: "Desperado", price: 2000 },
      { name: "Trophy", price: 2000 },
      { name: "Stout Extra Smooth", price: 2000 },
      { name: "Tiger", price: 2000 },
      { name: "Star", price: 2000 },
      { name: "Star Radler", price: 2000 },
      { name: "Double Black", price: 2000 },
      { name: "Orijin Beer", price: 2000 },
      { name: "Star lite", price: 1500 },
      { name: "Smirnoff Ice", price: 1500 },
      { name: "Trophy Stout", price: 2000 },
      { name: "Legend", price: 2000 },
      { name: "Legend (Medium)", price: 1500 },
      { name: "Legend (Twist)", price: 1500 },
      { name: "Gulder", price: 2000 },
      { name: "Castle Light", price: 2000 },
      { name: "Life", price: 2000 },
    ],
  },
  {
    category: "SPIRITS & LIQUORS",
    image: "/images/Jack-Daniels.jpeg",
    items: [
      { name: "Tequilla Olmeca", price: 60000 },
      { name: "Jameson", price: 40000 },
      { name: "Jameson Black", price: 60000 },
      { name: "Black Label", price: 60000 },
      { name: "Jack Daniel", price: 50000 },
      { name: "Gordon gin", price: 12000 },
      { name: "Hennessy VS", price: 150000 },
      { name: "Hennessy VSop", price: 200000 },
      { name: "Glenfiddich 12 Years", price: 120000 },
      { name: "Glenfiddich 18 Years", price: 230000 },
      { name: "Glenfiddich 21 Years", price: 327000 },
      { name: "Singleton 12 Years", price: 50000 },
      { name: "Williams Lawson", price: 30000 },
      { name: "Smirnoff vodka", price: 12000 },
      { name: "Baileys", price: 10000 },
      { name: "8PM", price: 15000 },
      { name: "Red Label", price: 30000 },
      { name: "Captain Jack", price: 12000 },
      { name: "Best Cream small", price: 4000 },
      { name: "Best Cream Big", price: 12000 },
      { name: "Black Label X1 (Small)", price: 70000 },
      { name: "X1 (Small)", price: 35000 },
      { name: "X1 (Big)", price: 12000 },
      { name: "Gordon Gin (Small)", price: 3500 },
      { name: "Absolute Vodka", price: 12000 },
      { name: "Campari", price: 40000 },
      { name: "Andre Rose", price: 20000 },
      { name: "Four cousins", price: 20000 },
      { name: "Carlos Rossi", price: 20000 },
      { name: "American Honey", price: 40000 },
      { name: "Martel Blue Swift", price: 190000 },
      { name: "Tenjaku Whiskey", price: 50000 },
      { name: "Drosdty HOF", price: 30000 },
      { name: "Black Bullet", price: 3000 },
      { name: "Orijin Bitters (Small)", price: 2000 },
      { name: "Ace Bitters", price: 2000 },
    ],
  },
  {
    category: "SHOTS LIQUORS",
    image: "/images/shots.jpeg",
    items: [
      { name: "Tequilla Shots", price: 3500 },
      { name: "Absolute Shots", price: 2500 },
      { name: "Gordon Gin Shots", price: 1500 },
      { name: "Campari shots", price: 2500 },
      { name: "Bacardi Shots", price: 3500 },
    ],
  },
  {
    category: "HOT BEVERAGES",
    image: "/images/Coffee.jpeg",
    items: [
      { name: "Tea", price: 1500 },
      { name: "Arabian Tea Half", price: 2500 },
      { name: "Arabian Tea Full", price: 4500 },
      { name: "Coffee", price: 1500 },
    ],
  },
  {
    category: "MILKSHAKE",
    image: "/images/Oreos-Milkshake.jpeg",
    items: [
      { name: "Strawberry milkshake", price: 6000 },
      { name: "Banana milkshake", price: 6000 },
      { name: "Vanilla milkshake", price: 6000 },
      { name: "Oreos Milkshake", price: 6000 },
      { name: "Fantasy Milkshake", price: 6000 },
    ],
  },
];
